image: Visual Studio 2017

version: 92.0.16-CI{build}

shallow_clone: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

#Cholatey install specific cmake
install:
  - cinst cmake.portable --version 3.11.4

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: .\build.ps1

# Disable tests
test: off

# artifacts:
#  - path: NuGet\*.nupkg
#    name: nupkgfiles

# Publish to myget feed
#deploy:
#  provider: NuGet
#  server: https://www.myget.org/F/cefsharp/api/v2/package
#  api_key:
#    secure: V8du2PPvMPok3Ya701jt5v2XWQgOZf52/H5wDHXBpKvXYkIIe8sonhVUy2TmEkqt
#  artifact: nupkgfiles
